spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/car_rental

    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #        hbm2ddl:
        #          auto: create
        temp:
          use_jdbc_metadata_defaults: false
  port: 8080
  spring:
    resources:
      add-mappings=true: